name: Build and attach release artifact

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITEA_PATH

      - name: Verify Bun
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Build with Vite
        run: bun run build

      - name: Create release archive
        run: cd build/; tar -cf release.tar.gz *

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ gitea.event.release.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip
