name: Build and attach release artifact

on:
  release:
    types:
      - published

jobs:
  build:
    uses: https://git.colormatic.org/colormaticstudios/actions/.gitea/workflows/sveltekit-bun-release.yml@main
    with:
      runner-label: colormatic-bun-ci-runner
      working-directory: .
      install-command: bun install --frozen-lockfile
      build-command: bun run build
      build-directory: build
      archive-name: release.tar.gz
    secrets:
      access_token: ${{ secrets.ACCESS_TOKEN }}
